CREATE TABLE IF NOT EXISTS MEMBER(
	ID VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20),
	NAME VARCHAR(30),
	PRIMARY KEY(ID)
);

INSERT INTO MEMBER VALUES('1', '1234', '홍길순');
INSERT INTO MEMBER VALUES('2', '1235', '홍길동');

SELECT * FROM MEMBER;

